react_native_path = './node_modules/react-native'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WKRN493' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod 'yoga', :path => react_native_path + '/ReactCommon/yoga'

  # Third party deps
  pod 'DoubleConversion', :podspec => react_native_path + '/third-party-podspecs/DoubleConversion.podspec'
  pod 'GLog', :podspec => react_native_path + '/third-party-podspecs/GLog.podspec'
  pod 'Folly', :podspec => react_native_path + '/third-party-podspecs/Folly.podspec'

  # You don't necessarily need all of these subspecs, but this would be a typical setup.
  pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'CxxBridge',
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    'RCTImage',
    'RCTNetwork',
    # Add any other subspecs you want to use in your project
    'DevSupport'
  ]



  target 'WKRN493Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WKRN493UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
